### ISSUE TITLE
[미해결] Cloudflare 에러, Yarn과 Npm 충돌 이슈

### ISSUE THREAD

**Issue by dusunax** [NyangGleNyangGle/NyangGle_Front_End#27]
### 문제 상황
- 문제점: 현재 배포를 위해 다음 과정을 진행하고 있습니다.
1. 기존 프로젝트 삭제(이전 프로젝트명과 겹치면 안되기 때문에 기존 프로젝트는 삭제)
2. Direct Upload를 선택
![image](https://user-images.githubusercontent.com/94776135/206865841-59be7394-ee72-4f8e-beb1-3d484b2f2fcb.png)
3. 프로젝트를 생성
![image](https://user-images.githubusercontent.com/94776135/206865860-31068408-26f6-453b-b2c3-89f84957431a.png)
4. 작업물을 VSC에서 `npm run build`로 /dist에 빌드
5. 빌드한 /dist내 파일을 업로드
![image](https://user-images.githubusercontent.com/94776135/206865908-0a54c67e-95bd-412c-b557-152d687e5827.png)
6. 업로드 완료 후 deloy site
![image](https://user-images.githubusercontent.com/94776135/206865940-4f7cae62-07b3-42ee-ba31-0b17c08e4911.png)
 
### 이슈 내용
- 백엔드와의 CORS 설정 때문에, 더 이상 local에서 test가 어렵습니다.
  - 매번 배포url와 localhost를 바꿔서 설정할 수 없음 
- 현재 프론트엔드 빌드와 배포에 문제가 있습니다.
  - 과정이 번거롭고 시간이 너무 오래걸리는 문제가 있습니다.
- cloudflare를 깃허브에 직접 연결하여 빌드하는 과정을 다시 시도해보았습니다.
  - 해당 과정에 npm과 yarn을 함께 사용하여 충돌 이슈가 있습니다.
  - 레퍼런스를 찾아본 결과, yarn과 npm을 혼용하면 추후 충돌이 생길 가능성이 높습니다.

### 에러 내용
- cloudflare 빌드 과정에서 에러가 발생합니다.
```jsx
00:49:16.005 | warning package-lock.json found. 
Your project contains lock files generated by tools 
other than Yarn. It is advised not to mix package managers 
in order to avoid resolution inconsistencies caused 
by unsynchronized lock files. To clear this warning, 
remove package-lock.json.
```

### 레퍼런스
⛔ **yarn과 npm을 혼용하면 안되는 이유**
- 패키지 관리 방식이 다르기 때문에 충돌이 생길 수 있습니다.
https://norwayy.tistory.com/390

### 수정 내용
- 에러 해결을 위해 package.lock.json파일 및 yarn 파일 삭제
  - package.json 파일만 남기고 다시 npm i 하였습니다.
- develop 브랜치에서 각 페이지 에러 여부 확인
  - npm run build 후 특이사항 또는 문제점 발견하지 못함
- cloudflare 에러 해결 확인을 위해 main 브랜치에 push 하였습니다.

=> 만약 문제 생긴다면 이전 파일로 덮어쓰기

### 추가 조사
=> 더 찾아보니 npm과 yarn을 같이 사용하는 사례가 있다고 합니다.
- https://stackoverflow.com/questions/49589493/is-there-any-harm-in-using-npm-and-yarn-in-the-same-project
  1) 만약 cloudflare를 Git과 연결하지 않고, 
  2) 이후의 충돌에 대한 고려가 필요없다면, 
  develop과 main의 package파일을 다시 덮어써야 할 것 같습니다. (내일 2시 이후 결정)

**Comment by dusunax** [comment]
## 추가에러
  - 이전에 발생한 이슈와 동일
  - #4
  - 해결하지 못한 이슈와 동일한 async, await 관련 에러 발생
```jsx
SyntaxError: Unexpected reserved word
--
01:34:57.350 | at Loader.moduleStrategy (internal/modules/esm/translators.js:81:18)
01:34:57.350 | at async link (internal/modules/esm/module_job.js:37:21)
01:34:57.356 | npm ERR! code ELIFECYCLE
01:34:57.356 | npm ERR! errno 1
01:34:57.357 | npm ERR! nyangnyang_letter@0.1.2 build: `vite build`
01:34:57.357 | npm ERR! Exit status 1
01:34:57.357 | npm ERR!
01:34:57.357 | npm ERR! Failed at the nyangnyang_letter@0.1.2 build script.
01:34:57.357 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
01:34:57.362 |  
01:34:57.362 | npm ERR! A complete log of this run can be found in:
01:34:57.362 | npm ERR!     /opt/buildhome/.npm/_logs/2022-12-10T16_34_57_358Z-debug.log
01:34:57.369 | Failed: build command exited with code: 1
01:34:58.412 | Failed: an internal error occurred
```

**Comment by dusunax** [comment]
## 해결
- 12/13 슈슈슝어피치 진행
- 설정
  - 프레임워크 : CRA
  - npm run build
  - /dist
  - 환경변수 하단과 같음
![image](https://user-images.githubusercontent.com/94776135/207404284-53f5cb84-77c5-438a-96cc-41286b6c2a79.png)
